#!/bin/sh

######################################################################

cd /root/abstracting

######################################################################

scheme=ypsilon

######################################################################

# abstracting [ --ypsilon | --larceny ]

######################################################################

while [ $# -gt 0 ]
do
  case $1
  in
    --ypsilon)
      scheme=ypsilon
      shift
    ;;

    --larceny)
      scheme=larceny
      shift
    ;;
  esac
done

######################################################################

if   [ $scheme = ypsilon ]
then
  cat src/boot/ypsilon/ypsilon.scm - | ypsilon
elif [ $scheme = larceny ]
then
  cat src/boot/larceny/larceny.scm - | larceny -err5rs
else
  exit
fi

