#!/bin/sh

######################################################################

cd /root/abstracting

######################################################################

scheme=ypsilon

######################################################################

while [ $# -gt 0 ]
do
  case $1
  in
    --ypsilon)
      scheme=ypsilon
      shift
    ;;

    --larceny)
      scheme=larceny
      shift
    ;;

    --ikarus)
      scheme=ikarus
      shift
    ;;

    --chicken)
      scheme=chicken
      shift
  esac
done

######################################################################

if   [ $scheme = ypsilon ]
then
  cat src/boot/ypsilon/ypsilon.scm - | ypsilon
elif [ $scheme = larceny ]
then
  cat src/boot/larceny/larceny.scm - | larceny -err5rs
elif [ $scheme = ikarus ]
then
  cat src/boot/ikarus/ikarus.scm - | ikarus
elif [ $scheme = chicken ]
then
  csi src/boot/chicken/chicken.scm
else
  exit
fi

