#!/bin/sh

######################################################################

cd /root/abstracting

######################################################################

scheme=ypsilon

######################################################################

while [ $# -gt 0 ]
do
  case $1
  in
    --ypsilon)
      scheme=ypsilon
      shift
    ;;

    --larceny)
      scheme=larceny
      shift
    ;;

    --ikarus)
      scheme=ikarus
      shift
    ;;

    --chicken)
      scheme=chicken
      shift
    ;;

    --gambit)
      scheme=gambit
      shift
  esac
done

######################################################################

if   [ $scheme = ypsilon ]
then
  ypsilon -i -- src/boot/ypsilon/ypsilon.scm
elif [ $scheme = larceny ]
then
  cat src/boot/larceny/larceny.scm - | larceny -path support/larceny -err5rs
elif [ $scheme = ikarus ]
then
  cat src/boot/ikarus/ikarus.scm - | ikarus
elif [ $scheme = chicken ]
then
  csi src/boot/chicken/chicken.scm
elif [ $scheme = gambit ]
then

  /usr/local/Gambit-C/bin/gsc           \
    -e '(load "~~lib/syntax-case.scm")' \
    -e '(include "src/boot/gambit/gambit.scm")' -

else
  exit
fi

