
(import (primitives r5rs:require))

(import (primitives system eval interaction-environment))

(r5rs:require 'xlib/xlib)

(import
 (primitives
  ;; structs
  make-XExtCodes
  XExtCodes-extension
  XExtCodes-major_opcode
  XExtCodes-first_event
  XExtCodes-first_error
  XExtCodes-extension-set!
  XExtCodes-major_opcode-set!
  XExtCodes-first_event-set!
  XExtCodes-first_error-set!
  make-XPixmapFormatValues
  XPixmapFormatValues-depth
  XPixmapFormatValues-bits_per_pixel
  XPixmapFormatValues-scanline_pad
  XPixmapFormatValues-depth-set!
  XPixmapFormatValues-bits_per_pixel-set!
  XPixmapFormatValues-scanline_pad-set!
  make-XGCValues
  XGCValues-function
  XGCValues-plane_mask
  XGCValues-foreground
  XGCValues-background
  XGCValues-line_width
  XGCValues-line_style
  XGCValues-cap_style
  XGCValues-join_style
  XGCValues-fill_style
  XGCValues-fill_rule
  XGCValues-arc_mode
  XGCValues-tile
  XGCValues-stipple
  XGCValues-ts_x_origin
  XGCValues-ts_y_origin
  XGCValues-font
  XGCValues-subwindow_mode
  XGCValues-graphics_exposures
  XGCValues-clip_x_origin
  XGCValues-clip_y_origin
  XGCValues-clip_mask
  XGCValues-dash_offset
  XGCValues-dashes
  XGCValues-function-set!
  XGCValues-plane_mask-set!
  XGCValues-foreground-set!
  XGCValues-background-set!
  XGCValues-line_width-set!
  XGCValues-line_style-set!
  XGCValues-cap_style-set!
  XGCValues-join_style-set!
  XGCValues-fill_style-set!
  XGCValues-fill_rule-set!
  XGCValues-arc_mode-set!
  XGCValues-tile-set!
  XGCValues-stipple-set!
  XGCValues-ts_x_origin-set!
  XGCValues-ts_y_origin-set!
  XGCValues-font-set!
  XGCValues-subwindow_mode-set!
  XGCValues-graphics_exposures-set!
  XGCValues-clip_x_origin-set!
  XGCValues-clip_y_origin-set!
  XGCValues-clip_mask-set!
  XGCValues-dash_offset-set!
  XGCValues-dashes-set!
  make-Visual
  Visual-ext_data
  Visual-visualid
  Visual-class
  Visual-red_mask
  Visual-green_mask
  Visual-blue_mask
  Visual-bits_per_rgb
  Visual-map_entries
  Visual-ext_data-set!
  Visual-visualid-set!
  Visual-class-set!
  Visual-red_mask-set!
  Visual-green_mask-set!
  Visual-blue_mask-set!
  Visual-bits_per_rgb-set!
  Visual-map_entries-set!
  make-Depth
  Depth-depth
  Depth-nvisuals
  Depth-visuals
  Depth-depth-set!
  Depth-nvisuals-set!
  Depth-visuals-set!
  make-Screen
  Screen-ext_data
  Screen-display
  Screen-root
  Screen-width
  Screen-height
  Screen-mwidth
  Screen-mheight
  Screen-ndepths
  Screen-depths
  Screen-root_depth
  Screen-root_visual
  Screen-default_gc
  Screen-cmap
  Screen-white_pixel
  Screen-black_pixel
  Screen-max_maps
  Screen-min_maps
  Screen-backing_store
  Screen-save_unders
  Screen-root_input_mask
  Screen-ext_data-set!
  Screen-display-set!
  Screen-root-set!
  Screen-width-set!
  Screen-height-set!
  Screen-mwidth-set!
  Screen-mheight-set!
  Screen-ndepths-set!
  Screen-depths-set!
  Screen-root_depth-set!
  Screen-root_visual-set!
  Screen-default_gc-set!
  Screen-cmap-set!
  Screen-white_pixel-set!
  Screen-black_pixel-set!
  Screen-max_maps-set!
  Screen-min_maps-set!
  Screen-backing_store-set!
  Screen-save_unders-set!
  Screen-root_input_mask-set!
  make-ScreenFormat
  ScreenFormat-ext_data
  ScreenFormat-depth
  ScreenFormat-bits_per_pixel
  ScreenFormat-scanline_pad
  ScreenFormat-ext_data-set!
  ScreenFormat-depth-set!
  ScreenFormat-bits_per_pixel-set!
  ScreenFormat-scanline_pad-set!
  make-XSetWindowAttributes
  XSetWindowAttributes-background_pixmap
  XSetWindowAttributes-background_pixel
  XSetWindowAttributes-border_pixmap
  XSetWindowAttributes-border_pixel
  XSetWindowAttributes-bit_gravity
  XSetWindowAttributes-win_gravity
  XSetWindowAttributes-backing_store
  XSetWindowAttributes-backing_planes
  XSetWindowAttributes-backing_pixel
  XSetWindowAttributes-save_under
  XSetWindowAttributes-event_mask
  XSetWindowAttributes-do_not_propagate_mask
  XSetWindowAttributes-override_redirect
  XSetWindowAttributes-colormap
  XSetWindowAttributes-cursor
  XSetWindowAttributes-background_pixmap-set!
  XSetWindowAttributes-background_pixel-set!
  XSetWindowAttributes-border_pixmap-set!
  XSetWindowAttributes-border_pixel-set!
  XSetWindowAttributes-bit_gravity-set!
  XSetWindowAttributes-win_gravity-set!
  XSetWindowAttributes-backing_store-set!
  XSetWindowAttributes-backing_planes-set!
  XSetWindowAttributes-backing_pixel-set!
  XSetWindowAttributes-save_under-set!
  XSetWindowAttributes-event_mask-set!
  XSetWindowAttributes-do_not_propagate_mask-set!
  XSetWindowAttributes-override_redirect-set!
  XSetWindowAttributes-colormap-set!
  XSetWindowAttributes-cursor-set!
  make-XWindowAttributes
  XWindowAttributes-x
  XWindowAttributes-y
  XWindowAttributes-width
  XWindowAttributes-height
  XWindowAttributes-border_width
  XWindowAttributes-depth
  XWindowAttributes-visual
  XWindowAttributes-root
  XWindowAttributes-class
  XWindowAttributes-bit_gravity
  XWindowAttributes-win_gravity
  XWindowAttributes-backing_store
  XWindowAttributes-backing_planes
  XWindowAttributes-backing_pixel
  XWindowAttributes-save_under
  XWindowAttributes-colormap
  XWindowAttributes-map_installed
  XWindowAttributes-map_state
  XWindowAttributes-all_event_masks
  XWindowAttributes-your_event_mask
  XWindowAttributes-do_not_propagate_mask
  XWindowAttributes-override_redirect
  XWindowAttributes-screen
  XWindowAttributes-x-set!
  XWindowAttributes-y-set!
  XWindowAttributes-width-set!
  XWindowAttributes-height-set!
  XWindowAttributes-border_width-set!
  XWindowAttributes-depth-set!
  XWindowAttributes-visual-set!
  XWindowAttributes-root-set!
  XWindowAttributes-class-set!
  XWindowAttributes-bit_gravity-set!
  XWindowAttributes-win_gravity-set!
  XWindowAttributes-backing_store-set!
  XWindowAttributes-backing_planes-set!
  XWindowAttributes-backing_pixel-set!
  XWindowAttributes-save_under-set!
  XWindowAttributes-colormap-set!
  XWindowAttributes-map_installed-set!
  XWindowAttributes-map_state-set!
  XWindowAttributes-all_event_masks-set!
  XWindowAttributes-your_event_mask-set!
  XWindowAttributes-do_not_propagate_mask-set!
  XWindowAttributes-override_redirect-set!
  XWindowAttributes-screen-set!
  make-XHostAddress
  XHostAddress-family
  XHostAddress-length
  XHostAddress-address
  XHostAddress-family-set!
  XHostAddress-length-set!
  XHostAddress-address-set!
  make-XServerInterpretedAddress
  XServerInterpretedAddress-typelength
  XServerInterpretedAddress-valuelength
  XServerInterpretedAddress-type
  XServerInterpretedAddress-value
  XServerInterpretedAddress-typelength-set!
  XServerInterpretedAddress-valuelength-set!
  XServerInterpretedAddress-type-set!
  XServerInterpretedAddress-value-set!
  make-XWindowChanges
  XWindowChanges-x
  XWindowChanges-y
  XWindowChanges-width
  XWindowChanges-height
  XWindowChanges-border_width
  XWindowChanges-sibling
  XWindowChanges-stack_mode
  XWindowChanges-x-set!
  XWindowChanges-y-set!
  XWindowChanges-width-set!
  XWindowChanges-height-set!
  XWindowChanges-border_width-set!
  XWindowChanges-sibling-set!
  XWindowChanges-stack_mode-set!
  make-XColor
  XColor-pixel
  XColor-red
  XColor-green
  XColor-blue
  XColor-flags
  XColor-pad
  XColor-pixel-set!
  XColor-red-set!
  XColor-green-set!
  XColor-blue-set!
  XColor-flags-set!
  XColor-pad-set!
  make-XSegment
  XSegment-x1
  XSegment-y1
  XSegment-x2
  XSegment-y2
  XSegment-x1-set!
  XSegment-y1-set!
  XSegment-x2-set!
  XSegment-y2-set!
  make-XPoint
  XPoint-x
  XPoint-y
  XPoint-x-set!
  XPoint-y-set!
  make-XRectangle
  XRectangle-x
  XRectangle-y
  XRectangle-width
  XRectangle-height
  XRectangle-x-set!
  XRectangle-y-set!
  XRectangle-width-set!
  XRectangle-height-set!
  make-XArc
  XArc-x
  XArc-y
  XArc-width
  XArc-height
  XArc-angle1
  XArc-angle2
  XArc-x-set!
  XArc-y-set!
  XArc-width-set!
  XArc-height-set!
  XArc-angle1-set!
  XArc-angle2-set!
  make-XKeyboardControl
  XKeyboardControl-key_click_percent
  XKeyboardControl-bell_percent
  XKeyboardControl-bell_pitch
  XKeyboardControl-bell_duration
  XKeyboardControl-led
  XKeyboardControl-led_mode
  XKeyboardControl-key
  XKeyboardControl-auto_repeat_mode
  XKeyboardControl-key_click_percent-set!
  XKeyboardControl-bell_percent-set!
  XKeyboardControl-bell_pitch-set!
  XKeyboardControl-bell_duration-set!
  XKeyboardControl-led-set!
  XKeyboardControl-led_mode-set!
  XKeyboardControl-key-set!
  XKeyboardControl-auto_repeat_mode-set!
  make-XTimeCoord
  XTimeCoord-time
  XTimeCoord-x
  XTimeCoord-y
  XTimeCoord-time-set!
  XTimeCoord-x-set!
  XTimeCoord-y-set!
  make-XModifierKeymap
  XModifierKeymap-max_keypermod
  XModifierKeymap-modifiermap
  XModifierKeymap-max_keypermod-set!
  XModifierKeymap-modifiermap-set!
  make-XKeyEvent
  XKeyEvent-type
  XKeyEvent-serial
  XKeyEvent-send_event
  XKeyEvent-display
  XKeyEvent-window
  XKeyEvent-root
  XKeyEvent-subwindow
  XKeyEvent-time
  XKeyEvent-x
  XKeyEvent-y
  XKeyEvent-x_root
  XKeyEvent-y_root
  XKeyEvent-state
  XKeyEvent-keycode
  XKeyEvent-same_screen
  XKeyEvent-type-set!
  XKeyEvent-serial-set!
  XKeyEvent-send_event-set!
  XKeyEvent-display-set!
  XKeyEvent-window-set!
  XKeyEvent-root-set!
  XKeyEvent-subwindow-set!
  XKeyEvent-time-set!
  XKeyEvent-x-set!
  XKeyEvent-y-set!
  XKeyEvent-x_root-set!
  XKeyEvent-y_root-set!
  XKeyEvent-state-set!
  XKeyEvent-keycode-set!
  XKeyEvent-same_screen-set!
  make-XButtonEvent
  XButtonEvent-type
  XButtonEvent-serial
  XButtonEvent-send_event
  XButtonEvent-display
  XButtonEvent-window
  XButtonEvent-root
  XButtonEvent-subwindow
  XButtonEvent-time
  XButtonEvent-x
  XButtonEvent-y
  XButtonEvent-x_root
  XButtonEvent-y_root
  XButtonEvent-state
  XButtonEvent-button
  XButtonEvent-same_screen
  XButtonEvent-type-set!
  XButtonEvent-serial-set!
  XButtonEvent-send_event-set!
  XButtonEvent-display-set!
  XButtonEvent-window-set!
  XButtonEvent-root-set!
  XButtonEvent-subwindow-set!
  XButtonEvent-time-set!
  XButtonEvent-x-set!
  XButtonEvent-y-set!
  XButtonEvent-x_root-set!
  XButtonEvent-y_root-set!
  XButtonEvent-state-set!
  XButtonEvent-button-set!
  XButtonEvent-same_screen-set!
  make-XMotionEvent
  XMotionEvent-type
  XMotionEvent-serial
  XMotionEvent-send_event
  XMotionEvent-display
  XMotionEvent-window
  XMotionEvent-root
  XMotionEvent-subwindow
  XMotionEvent-time
  XMotionEvent-x
  XMotionEvent-y
  XMotionEvent-x_root
  XMotionEvent-y_root
  XMotionEvent-state
  XMotionEvent-is_hint
  XMotionEvent-same_screen
  XMotionEvent-type-set!
  XMotionEvent-serial-set!
  XMotionEvent-send_event-set!
  XMotionEvent-display-set!
  XMotionEvent-window-set!
  XMotionEvent-root-set!
  XMotionEvent-subwindow-set!
  XMotionEvent-time-set!
  XMotionEvent-x-set!
  XMotionEvent-y-set!
  XMotionEvent-x_root-set!
  XMotionEvent-y_root-set!
  XMotionEvent-state-set!
  XMotionEvent-is_hint-set!
  XMotionEvent-same_screen-set!
  make-XCrossingEvent
  XCrossingEvent-type
  XCrossingEvent-serial
  XCrossingEvent-send_event
  XCrossingEvent-display
  XCrossingEvent-window
  XCrossingEvent-root
  XCrossingEvent-subwindow
  XCrossingEvent-time
  XCrossingEvent-x
  XCrossingEvent-y
  XCrossingEvent-x_root
  XCrossingEvent-y_root
  XCrossingEvent-mode
  XCrossingEvent-detail
  XCrossingEvent-same_screen
  XCrossingEvent-focus
  XCrossingEvent-state
  XCrossingEvent-type-set!
  XCrossingEvent-serial-set!
  XCrossingEvent-send_event-set!
  XCrossingEvent-display-set!
  XCrossingEvent-window-set!
  XCrossingEvent-root-set!
  XCrossingEvent-subwindow-set!
  XCrossingEvent-time-set!
  XCrossingEvent-x-set!
  XCrossingEvent-y-set!
  XCrossingEvent-x_root-set!
  XCrossingEvent-y_root-set!
  XCrossingEvent-mode-set!
  XCrossingEvent-detail-set!
  XCrossingEvent-same_screen-set!
  XCrossingEvent-focus-set!
  XCrossingEvent-state-set!
  make-XFocusChangeEvent
  XFocusChangeEvent-type
  XFocusChangeEvent-serial
  XFocusChangeEvent-send_event
  XFocusChangeEvent-display
  XFocusChangeEvent-window
  XFocusChangeEvent-mode
  XFocusChangeEvent-detail
  XFocusChangeEvent-type-set!
  XFocusChangeEvent-serial-set!
  XFocusChangeEvent-send_event-set!
  XFocusChangeEvent-display-set!
  XFocusChangeEvent-window-set!
  XFocusChangeEvent-mode-set!
  XFocusChangeEvent-detail-set!
  make-XExposeEvent
  XExposeEvent-type
  XExposeEvent-serial
  XExposeEvent-send_event
  XExposeEvent-display
  XExposeEvent-window
  XExposeEvent-x
  XExposeEvent-y
  XExposeEvent-width
  XExposeEvent-height
  XExposeEvent-count
  XExposeEvent-type-set!
  XExposeEvent-serial-set!
  XExposeEvent-send_event-set!
  XExposeEvent-display-set!
  XExposeEvent-window-set!
  XExposeEvent-x-set!
  XExposeEvent-y-set!
  XExposeEvent-width-set!
  XExposeEvent-height-set!
  XExposeEvent-count-set!
  make-XGraphicsExposeEvent
  XGraphicsExposeEvent-type
  XGraphicsExposeEvent-serial
  XGraphicsExposeEvent-send_event
  XGraphicsExposeEvent-display
  XGraphicsExposeEvent-drawable
  XGraphicsExposeEvent-x
  XGraphicsExposeEvent-y
  XGraphicsExposeEvent-width
  XGraphicsExposeEvent-height
  XGraphicsExposeEvent-count
  XGraphicsExposeEvent-major_code
  XGraphicsExposeEvent-minor_code
  XGraphicsExposeEvent-type-set!
  XGraphicsExposeEvent-serial-set!
  XGraphicsExposeEvent-send_event-set!
  XGraphicsExposeEvent-display-set!
  XGraphicsExposeEvent-drawable-set!
  XGraphicsExposeEvent-x-set!
  XGraphicsExposeEvent-y-set!
  XGraphicsExposeEvent-width-set!
  XGraphicsExposeEvent-height-set!
  XGraphicsExposeEvent-count-set!
  XGraphicsExposeEvent-major_code-set!
  XGraphicsExposeEvent-minor_code-set!
  make-XNoExposeEvent
  XNoExposeEvent-type
  XNoExposeEvent-serial
  XNoExposeEvent-send_event
  XNoExposeEvent-display
  XNoExposeEvent-drawable
  XNoExposeEvent-major_code
  XNoExposeEvent-minor_code
  XNoExposeEvent-type-set!
  XNoExposeEvent-serial-set!
  XNoExposeEvent-send_event-set!
  XNoExposeEvent-display-set!
  XNoExposeEvent-drawable-set!
  XNoExposeEvent-major_code-set!
  XNoExposeEvent-minor_code-set!
  make-XVisibilityEvent
  XVisibilityEvent-type
  XVisibilityEvent-serial
  XVisibilityEvent-send_event
  XVisibilityEvent-display
  XVisibilityEvent-window
  XVisibilityEvent-state
  XVisibilityEvent-type-set!
  XVisibilityEvent-serial-set!
  XVisibilityEvent-send_event-set!
  XVisibilityEvent-display-set!
  XVisibilityEvent-window-set!
  XVisibilityEvent-state-set!
  make-XCreateWindowEvent
  XCreateWindowEvent-type
  XCreateWindowEvent-serial
  XCreateWindowEvent-send_event
  XCreateWindowEvent-display
  XCreateWindowEvent-parent
  XCreateWindowEvent-window
  XCreateWindowEvent-x
  XCreateWindowEvent-y
  XCreateWindowEvent-width
  XCreateWindowEvent-height
  XCreateWindowEvent-border_width
  XCreateWindowEvent-override_redirect
  XCreateWindowEvent-type-set!
  XCreateWindowEvent-serial-set!
  XCreateWindowEvent-send_event-set!
  XCreateWindowEvent-display-set!
  XCreateWindowEvent-parent-set!
  XCreateWindowEvent-window-set!
  XCreateWindowEvent-x-set!
  XCreateWindowEvent-y-set!
  XCreateWindowEvent-width-set!
  XCreateWindowEvent-height-set!
  XCreateWindowEvent-border_width-set!
  XCreateWindowEvent-override_redirect-set!
  make-XDestroyWindowEvent
  XDestroyWindowEvent-type
  XDestroyWindowEvent-serial
  XDestroyWindowEvent-send_event
  XDestroyWindowEvent-display
  XDestroyWindowEvent-event
  XDestroyWindowEvent-window
  XDestroyWindowEvent-type-set!
  XDestroyWindowEvent-serial-set!
  XDestroyWindowEvent-send_event-set!
  XDestroyWindowEvent-display-set!
  XDestroyWindowEvent-event-set!
  XDestroyWindowEvent-window-set!
  make-XUnmapEvent
  XUnmapEvent-type
  XUnmapEvent-serial
  XUnmapEvent-send_event
  XUnmapEvent-display
  XUnmapEvent-event
  XUnmapEvent-window
  XUnmapEvent-from_configure
  XUnmapEvent-type-set!
  XUnmapEvent-serial-set!
  XUnmapEvent-send_event-set!
  XUnmapEvent-display-set!
  XUnmapEvent-event-set!
  XUnmapEvent-window-set!
  XUnmapEvent-from_configure-set!
  make-XMapEvent
  XMapEvent-type
  XMapEvent-serial
  XMapEvent-send_event
  XMapEvent-display
  XMapEvent-event
  XMapEvent-window
  XMapEvent-override_redirect
  XMapEvent-type-set!
  XMapEvent-serial-set!
  XMapEvent-send_event-set!
  XMapEvent-display-set!
  XMapEvent-event-set!
  XMapEvent-window-set!
  XMapEvent-override_redirect-set!
  make-XMapRequestEvent
  XMapRequestEvent-type
  XMapRequestEvent-serial
  XMapRequestEvent-send_event
  XMapRequestEvent-display
  XMapRequestEvent-parent
  XMapRequestEvent-window
  XMapRequestEvent-type-set!
  XMapRequestEvent-serial-set!
  XMapRequestEvent-send_event-set!
  XMapRequestEvent-display-set!
  XMapRequestEvent-parent-set!
  XMapRequestEvent-window-set!
  make-XReparentEvent
  XReparentEvent-type
  XReparentEvent-serial
  XReparentEvent-send_event
  XReparentEvent-display
  XReparentEvent-event
  XReparentEvent-window
  XReparentEvent-parent
  XReparentEvent-x
  XReparentEvent-y
  XReparentEvent-override_redirect
  XReparentEvent-type-set!
  XReparentEvent-serial-set!
  XReparentEvent-send_event-set!
  XReparentEvent-display-set!
  XReparentEvent-event-set!
  XReparentEvent-window-set!
  XReparentEvent-parent-set!
  XReparentEvent-x-set!
  XReparentEvent-y-set!
  XReparentEvent-override_redirect-set!
  make-XConfigureEvent
  XConfigureEvent-type
  XConfigureEvent-serial
  XConfigureEvent-send_event
  XConfigureEvent-display
  XConfigureEvent-event
  XConfigureEvent-window
  XConfigureEvent-x
  XConfigureEvent-y
  XConfigureEvent-width
  XConfigureEvent-height
  XConfigureEvent-border_width
  XConfigureEvent-above
  XConfigureEvent-override_redirect
  XConfigureEvent-type-set!
  XConfigureEvent-serial-set!
  XConfigureEvent-send_event-set!
  XConfigureEvent-display-set!
  XConfigureEvent-event-set!
  XConfigureEvent-window-set!
  XConfigureEvent-x-set!
  XConfigureEvent-y-set!
  XConfigureEvent-width-set!
  XConfigureEvent-height-set!
  XConfigureEvent-border_width-set!
  XConfigureEvent-above-set!
  XConfigureEvent-override_redirect-set!
  make-XGravityEvent
  XGravityEvent-type
  XGravityEvent-serial
  XGravityEvent-send_event
  XGravityEvent-display
  XGravityEvent-event
  XGravityEvent-window
  XGravityEvent-x
  XGravityEvent-y
  XGravityEvent-type-set!
  XGravityEvent-serial-set!
  XGravityEvent-send_event-set!
  XGravityEvent-display-set!
  XGravityEvent-event-set!
  XGravityEvent-window-set!
  XGravityEvent-x-set!
  XGravityEvent-y-set!
  make-XResizeRequestEvent
  XResizeRequestEvent-type
  XResizeRequestEvent-serial
  XResizeRequestEvent-send_event
  XResizeRequestEvent-display
  XResizeRequestEvent-window
  XResizeRequestEvent-width
  XResizeRequestEvent-height
  XResizeRequestEvent-type-set!
  XResizeRequestEvent-serial-set!
  XResizeRequestEvent-send_event-set!
  XResizeRequestEvent-display-set!
  XResizeRequestEvent-window-set!
  XResizeRequestEvent-width-set!
  XResizeRequestEvent-height-set!
  make-XConfigureRequestEvent
  XConfigureRequestEvent-type
  XConfigureRequestEvent-serial
  XConfigureRequestEvent-send_event
  XConfigureRequestEvent-display
  XConfigureRequestEvent-parent
  XConfigureRequestEvent-window
  XConfigureRequestEvent-x
  XConfigureRequestEvent-y
  XConfigureRequestEvent-width
  XConfigureRequestEvent-height
  XConfigureRequestEvent-border_width
  XConfigureRequestEvent-above
  XConfigureRequestEvent-detail
  XConfigureRequestEvent-value_mask
  XConfigureRequestEvent-type-set!
  XConfigureRequestEvent-serial-set!
  XConfigureRequestEvent-send_event-set!
  XConfigureRequestEvent-display-set!
  XConfigureRequestEvent-parent-set!
  XConfigureRequestEvent-window-set!
  XConfigureRequestEvent-x-set!
  XConfigureRequestEvent-y-set!
  XConfigureRequestEvent-width-set!
  XConfigureRequestEvent-height-set!
  XConfigureRequestEvent-border_width-set!
  XConfigureRequestEvent-above-set!
  XConfigureRequestEvent-detail-set!
  XConfigureRequestEvent-value_mask-set!
  make-XCirculateEvent
  XCirculateEvent-type
  XCirculateEvent-serial
  XCirculateEvent-send_event
  XCirculateEvent-display
  XCirculateEvent-event
  XCirculateEvent-window
  XCirculateEvent-place
  XCirculateEvent-type-set!
  XCirculateEvent-serial-set!
  XCirculateEvent-send_event-set!
  XCirculateEvent-display-set!
  XCirculateEvent-event-set!
  XCirculateEvent-window-set!
  XCirculateEvent-place-set!
  make-XCirculateRequestEvent
  XCirculateRequestEvent-type
  XCirculateRequestEvent-serial
  XCirculateRequestEvent-send_event
  XCirculateRequestEvent-display
  XCirculateRequestEvent-parent
  XCirculateRequestEvent-window
  XCirculateRequestEvent-place
  XCirculateRequestEvent-type-set!
  XCirculateRequestEvent-serial-set!
  XCirculateRequestEvent-send_event-set!
  XCirculateRequestEvent-display-set!
  XCirculateRequestEvent-parent-set!
  XCirculateRequestEvent-window-set!
  XCirculateRequestEvent-place-set!
  make-XPropertyEvent
  XPropertyEvent-type
  XPropertyEvent-serial
  XPropertyEvent-send_event
  XPropertyEvent-display
  XPropertyEvent-window
  XPropertyEvent-atom
  XPropertyEvent-time
  XPropertyEvent-state
  XPropertyEvent-type-set!
  XPropertyEvent-serial-set!
  XPropertyEvent-send_event-set!
  XPropertyEvent-display-set!
  XPropertyEvent-window-set!
  XPropertyEvent-atom-set!
  XPropertyEvent-time-set!
  XPropertyEvent-state-set!
  make-XSelectionClearEvent
  XSelectionClearEvent-type
  XSelectionClearEvent-serial
  XSelectionClearEvent-send_event
  XSelectionClearEvent-display
  XSelectionClearEvent-window
  XSelectionClearEvent-selection
  XSelectionClearEvent-time
  XSelectionClearEvent-type-set!
  XSelectionClearEvent-serial-set!
  XSelectionClearEvent-send_event-set!
  XSelectionClearEvent-display-set!
  XSelectionClearEvent-window-set!
  XSelectionClearEvent-selection-set!
  XSelectionClearEvent-time-set!
  make-XSelectionRequestEvent
  XSelectionRequestEvent-type
  XSelectionRequestEvent-serial
  XSelectionRequestEvent-send_event
  XSelectionRequestEvent-display
  XSelectionRequestEvent-owner
  XSelectionRequestEvent-requestor
  XSelectionRequestEvent-selection
  XSelectionRequestEvent-target
  XSelectionRequestEvent-property
  XSelectionRequestEvent-time
  XSelectionRequestEvent-type-set!
  XSelectionRequestEvent-serial-set!
  XSelectionRequestEvent-send_event-set!
  XSelectionRequestEvent-display-set!
  XSelectionRequestEvent-owner-set!
  XSelectionRequestEvent-requestor-set!
  XSelectionRequestEvent-selection-set!
  XSelectionRequestEvent-target-set!
  XSelectionRequestEvent-property-set!
  XSelectionRequestEvent-time-set!
  make-XSelectionEvent
  XSelectionEvent-type
  XSelectionEvent-serial
  XSelectionEvent-send_event
  XSelectionEvent-display
  XSelectionEvent-requestor
  XSelectionEvent-selection
  XSelectionEvent-target
  XSelectionEvent-property
  XSelectionEvent-time
  XSelectionEvent-type-set!
  XSelectionEvent-serial-set!
  XSelectionEvent-send_event-set!
  XSelectionEvent-display-set!
  XSelectionEvent-requestor-set!
  XSelectionEvent-selection-set!
  XSelectionEvent-target-set!
  XSelectionEvent-property-set!
  XSelectionEvent-time-set!
  make-XColormapEvent
  XColormapEvent-type
  XColormapEvent-serial
  XColormapEvent-send_event
  XColormapEvent-display
  XColormapEvent-window
  XColormapEvent-colormap
  XColormapEvent-new
  XColormapEvent-state
  XColormapEvent-type-set!
  XColormapEvent-serial-set!
  XColormapEvent-send_event-set!
  XColormapEvent-display-set!
  XColormapEvent-window-set!
  XColormapEvent-colormap-set!
  XColormapEvent-new-set!
  XColormapEvent-state-set!
  make-XMappingEvent
  XMappingEvent-type
  XMappingEvent-serial
  XMappingEvent-send_event
  XMappingEvent-display
  XMappingEvent-window
  XMappingEvent-request
  XMappingEvent-first_keycode
  XMappingEvent-count
  XMappingEvent-type-set!
  XMappingEvent-serial-set!
  XMappingEvent-send_event-set!
  XMappingEvent-display-set!
  XMappingEvent-window-set!
  XMappingEvent-request-set!
  XMappingEvent-first_keycode-set!
  XMappingEvent-count-set!
  make-XErrorEvent
  XErrorEvent-type
  XErrorEvent-display
  XErrorEvent-resourceid
  XErrorEvent-serial
  XErrorEvent-error_code
  XErrorEvent-request_code
  XErrorEvent-minor_code
  XErrorEvent-type-set!
  XErrorEvent-display-set!
  XErrorEvent-resourceid-set!
  XErrorEvent-serial-set!
  XErrorEvent-error_code-set!
  XErrorEvent-request_code-set!
  XErrorEvent-minor_code-set!
  make-XAnyEvent
  XAnyEvent-type
  XAnyEvent-serial
  XAnyEvent-send_event
  XAnyEvent-display
  XAnyEvent-window
  XAnyEvent-type-set!
  XAnyEvent-serial-set!
  XAnyEvent-send_event-set!
  XAnyEvent-display-set!
  XAnyEvent-window-set!
  make-XCharStruct
  XCharStruct-lbearing
  XCharStruct-rbearing
  XCharStruct-width
  XCharStruct-ascent
  XCharStruct-descent
  XCharStruct-attributes
  XCharStruct-lbearing-set!
  XCharStruct-rbearing-set!
  XCharStruct-width-set!
  XCharStruct-ascent-set!
  XCharStruct-descent-set!
  XCharStruct-attributes-set!
  make-XFontProp
  XFontProp-name
  XFontProp-card32
  XFontProp-name-set!
  XFontProp-card32-set!
  make-XTextItem
  XTextItem-chars
  XTextItem-nchars
  XTextItem-delta
  XTextItem-font
  XTextItem-chars-set!
  XTextItem-nchars-set!
  XTextItem-delta-set!
  XTextItem-font-set!
  make-XChar2b
  XChar2b-byte1
  XChar2b-byte2
  XChar2b-byte1-set!
  XChar2b-byte2-set!
  make-XTextItem16
  XTextItem16-chars
  XTextItem16-nchars
  XTextItem16-delta
  XTextItem16-font
  XTextItem16-chars-set!
  XTextItem16-nchars-set!
  XTextItem16-delta-set!
  XTextItem16-font-set!
  ;; functions
  XLoadQueryFont
  XQueryFont
  XGetMotionEvents
  XDeleteModifiermapEntry
  XGetModifierMapping
  XInsertModifiermapEntry
  XNewModifiermap
  XCreateImage
  XInitImage
  XGetImage
  XGetSubImage
  XOpenDisplay
  XrmInitialize
  XFetchBytes
  XFetchBuffer
  XGetAtomName
  XGetAtomNames
  XGetDefault
  XDisplayName
  XKeysymToString
  XInternAtom
  XInternAtoms
  XCopyColormapAndFree
  XCreateColormap
  XCreatePixmapCursor
  XCreateGlyphCursor
  XCreateFontCursor
  XLoadFont
  XCreateGC
  XGContextFromGC
  XFlushGC
  XCreatePixmap
  XCreateBitmapFromData
  XCreatePixmapFromBitmapData
  XCreateSimpleWindow
  XGetSelectionOwner
  XCreateWindow
  XListInstalledColormaps
  XListFonts
  XListFontsWithInfo
  XGetFontPath
  XListExtensions
  XListProperties
  XListHosts
  XKeycodeToKeysym
  XLookupKeysym
  XGetKeyboardMapping
  XStringToKeysym
  XMaxRequestSize
  XExtendedMaxRequestSize
  XResourceManagerString
  XScreenResourceString
  XDisplayMotionBufferSize
  XVisualIDFromVisual
  XInitThreads
  XLockDisplay
  XUnlockDisplay
  XInitExtension
  XAddExtension
  XFindOnExtensionList

  XRootWindow
  XDefaultRootWindow
  XRootWindowOfScreen
  XDefaultVisual
  XDefaultVisualOfScreen
  XDefaultGC
  XDefaultGCOfScreen
  XBlackPixel
  XWhitePixel
  XAllPlanes
  XBlackPixelOfScreen
  XWhitePixelOfScreen
  XNextRequest
  XLastKnownRequestProcessed
  XServerVendor
  XDisplayString
  XDefaultColormap
  XDefaultColormapOfScreen
  XDisplayOfScreen
  XScreenOfDisplay
  XDefaultScreenOfDisplay
  XEventMaskOfScreen
  XScreenNumberOfScreen
  XSetErrorHandler
  ;; XSetIOErrorHandler
  XListPixmapFormats
  ;; XListDepths
  XReconfigureWMWindow
  XGetWMProtocols
  XSetWMProtocols
  XIconifyWindow
  XWithdrawWindow
  XGetCommand
  XGetWMColormapWindows
  XSetWMColormapWindows
  XFreeStringList
  XSetTransientForHint
  XActivateScreenSaver
  XAddHost
  XAddHosts
  ;; XAddToExtensionList
  XAddToSaveSet
  XAllocColor
  XAllocColorCells
  XAllocColorPlanes
  XAllocNamedColor
  XAllowEvents
  XAutoRepeatOff
  XAutoRepeatOn
  XBell
  XBitmapBitOrder
  XBitmapPad
  XBitmapUnit
  XCellsOfScreen
  XChangeActivePointerGrab
  XChangeGC
  XChangeKeyboardControl
  XChangeKeyboardMapping
  XChangePointerControl
  XChangeProperty
  XChangeSaveSet
  XChangeWindowAttributes
  ;; XCheckIfEvent
  XCheckMaskEvent
  XCheckTypedEvent
  XCheckTypedWindowEvent
  XCheckWindowEvent
  XCirculateSubwindows
  XCirculateSubwindowsDown
  XCirculateSubwindowsUp
  XClearArea
  XClearWindow
  XCloseDisplay
  XConfigureWindow
  XConnectionNumber
  XConvertSelection
  XCopyArea
  XCopyGC
  XCopyPlane
  XDefaultDepth
  XDefaultDepthOfScreen
  XDefaultScreen
  XDefineCursor
  XDeleteProperty
  XDestroyWindow
  XDestroySubwindows
  XDoesBackingStore
  XDoesSaveUnders
  XDisableAccessControl
  XDisplayCells
  XDisplayHeight
  XDisplayHeightMM
  XDisplayKeycodes
  XDisplayPlanes
  XDisplayWidth
  XDisplayWidthMM
  XDrawArc
  XDrawArcs
  XDrawImageString
  XDrawImageString16
  XDrawLine
  XDrawLines
  XDrawPoint
  XDrawPoints
  XDrawRectangle
  XDrawRectangles
  XDrawSegments
  XDrawString
  XDrawString16
  XDrawText
  XDrawText16
  XEnableAccessControl
  XEventsQueued
  XFetchName
  XFillArc
  XFillArcs
  XFillPolygon
  XFillRectangle
  XFillRectangles
  XFlush
  XForceScreenSaver
  XFree
  XFreeColormap
  XFreeColors
  XFreeCursor
  XFreeExtensionList
  XFreeFont
  XFreeFontInfo
  XFreeFontNames
  XFreeFontPath
  XFreeGC
  XFreeModifiermap
  XFreePixmap
  XGeometry
  XGetErrorDatabaseText
  XGetErrorText
  XGetFontProperty
  XGetGCValues
  XGetGeometry
  XGetIconName
  XGetInputFocus
  XGetKeyboardControl
  XGetPointerControl
  XGetPointerMapping
  XGetScreenSaver
  XGetTransientForHint
  XGetWindowProperty
  XGetWindowAttributes
  XGrabButton
  XGrabKey
  XGrabKeyboard
  XGrabPointer
  XGrabServer
  XHeightMMOfScreen
  XHeightOfScreen
  ;; XIfEvent
  XImageByteOrder
  XInstallColormap
  XKeysymToKeycode
  XKillClient
  XLookupColor
  XLowerWindow
  XMapRaised
  XMapSubwindows
  XMapWindow
  XMaskEvent
  XMaxCmapsOfScreen
  XMinCmapsOfScreen
  XMoveResizeWindow
  XMoveWindow
  XNextEvent
  XNoOp
  XParseColor
  XParseGeometry
  ;; XPeekEvent
  ;; XPeekIfEvent
  XPending
  XPlanesOfScreen
  XProtocolRevision
  XProtocolVersion
  XPutBackEvent
  XPutImage
  XQLength
  XQueryBestCursor
  XQueryBestSize
  XQueryBestStipple
  XQueryBestTile
  XQueryColor
  XQueryColors
  XQueryExtension
  ;; XQueryKeymap
  XQueryPointer
  XQueryTextExtents
  XQueryTextExtents16
  XQueryTree
  XRaiseWindow
  XReadBitmapFile
  XReadBitmapFileData
  XRebindKeysym
  XRecolorCursor
  XRefreshKeyboardMapping
  XRemoveFromSaveSet
  XRemoveHost
  XRemoveHosts
  XReparentWindow
  XResetScreenSaver
  XResizeWindow
  XRestackWindows
  XRotateBuffers
  XRotateWindowProperties
  XScreenCount
  XSelectInput
  XSendEvent
  XSetAccessControl
  XSetArcMode
  XSetBackground
  XSetClipMask
  XSetClipOrigin
  XSetClipRectangles
  XSetCloseDownMode
  XSetCommand
  XSetDashes
  XSetFillRule
  XSetFillStyle
  XSetFont
  XSetFontPath
  XSetForeground
  XSetFunction
  XSetGraphicsExposures
  XSetIconName
  XSetInputFocus
  XSetLineAttributes
  XSetModifierMapping
  XSetPlaneMask
  XSetPointerMapping
  XSetScreenSaver
  XSetSelectionOwner
  XSetState
  XSetStipple
  XSetSubwindowMode
  XSetTSOrigin
  XSetTile
  XSetWindowBackground
  XSetWindowBackgroundPixmap
  XSetWindowBorder
  XSetWindowBorderPixmap
  XSetWindowBorderWidth
  XSetWindowColormap
  XStoreBuffer
  XStoreBytes
  XStoreColor
  XStoreColors
  XStoreName
  XStoreNamedColor
  XSync
  XTextExtents
  XTextExtents16
  XTextWidth
  XTextWidth16
  XTranslateCoordinates
  XUndefineCursor
  XUngrabButton
  XUngrabKey
  XUngrabKeyboard
  XUngrabPointer
  XUngrabServer
  XUninstallColormap
  XUnloadFont
  XUnmapSubwindows
  XUnmapWindow
  XVendorRelease
  XWarpPointer
  XWidthMMOfScreen
  XWidthOfScreen
  XWindowEvent
  XWriteBitmapFile
  XSupportsLocale
  XSetLocaleModifiers
  ;; XOpenOM
  XCreateFontSet
  XFreeFontSet
  XFontsOfFontSet
  XBaseFontNameListOfFontSet
  XLocaleOfFontSet
  XContextDependentDrawing
  XDirectionalDependentDrawing
  XContextualDrawing
  XExtentsOfFontSet
  XmbTextEscapement
  XwcTextEscapement
  Xutf8TextEscapement
  XmbTextExtents
  XwcTextExtents
  Xutf8TextExtents
  XmbTextPerCharExtents
  XwcTextPerCharExtents
  Xutf8TextPerCharExtents
  XmbDrawText
  XwcDrawText
  Xutf8DrawText
  XmbDrawString
  XwcDrawString
  Xutf8DrawString
  XmbDrawImageString
  XwcDrawImageString
  Xutf8DrawImageString
  ;; XOpenIM
  XCloseIM
  XDisplayOfIM
  XLocaleOfIM
  XDestroyIC
  XSetICFocus
  XUnsetICFocus
  XwcResetIC
  XmbResetIC
  Xutf8ResetIC
  XIMOfIC
  XFilterEvent
  XmbLookupString
  XwcLookupString
  Xutf8LookupString
  ;; XRegisterIMInstantiateCallback
  ;; XUnregisterIMInstantiateCallback
  XInternalConnectionNumbers
  XProcessInternalConnection
  ;; XAddConnectionWatch
  ;; XRemoveConnectionWatch
  XSetAuthorization
  ;; _Xmbtowc
  ;; _Xwctomb

  XlibSpecificationRelease

  True
  False
  QueuedAlready
  QueuedAfterReading
  QueuedAfterFlush

  XNRequiredCharSet
  XNQueryOrientation
  XNBaseFontName
  XNOMAutomatic
  XNMissingCharSet
  XNDefaultString
  XNOrientation
  XNDirectionalDependentDrawing
  XNContextualDrawing
  XNFontInfo
  XIMPreeditArea
  XIMPreeditCallbacks
  XIMPreeditPosition
  XIMPreeditNothing
  XIMPreeditNone
  XIMStatusArea
  XIMStatusCallbacks
  XIMStatusNothing
  XIMStatusNone
  XNVaNestedList
  XNQueryInputStyle
  XNClientWindow
  XNInputStyle
  XNFocusWindow
  XNResourceName
  XNResourceClass
  XNGeometryCallback
  XNDestroyCallback
  XNFilterEvents
  XNPreeditStartCallback
  XNPreeditDoneCallback
  XNPreeditDrawCallback
  XNPreeditCaretCallback
  XNPreeditStateNotifyCallback
  XNPreeditAttributes
  XNStatusStartCallback
  XNStatusDoneCallback
  XNStatusDrawCallback
  XNStatusAttributes
  XNArea
  XNAreaNeeded
  XNSpotLocation
  XNColormap
  XNStdColormap
  XNForeground
  XNBackground
  XNBackgroundPixmap
  XNFontSet
  XNLineSpace
  XNCursor
  XNQueryIMValuesList
  XNQueryICValuesList
  XNVisiblePosition
  XNR6PreeditCallback
  XNStringConversionCallback
  XNStringConversion
  XNResetState
  XNHotKey
  XNHotKeyState
  XNPreeditState
  XNSeparatorofNestedList
  XBufferOverflow
  XLookupNone
  XLookupChars
  XLookupKeySym
  XLookupBoth
  XIMReverse
  XIMUnderline
  XIMHighlight
  XIMPrimary
  XIMSecondary
  XIMTertiary
  XIMVisibleToForward
  XIMVisibleToBackword
  XIMVisibleToCenter
  XIMPreeditUnKnown
  XIMPreeditEnable
  XIMPreeditDisable
  XIMInitialState
  XIMPreserveState

  XIMStringConversionLeftEdge
  XIMStringConversionRightEdge
  XIMStringConversionTopEdge
  XIMStringConversionBottomEdge
  XIMStringConversionConcealed
  XIMStringConversionWrapped
  XIMStringConversionBuffer
  XIMStringConversionLine
  XIMStringConversionWord
  XIMStringConversionChar
  XIMStringConversionSubstitution
  XIMStringConversionRetrieval
  XIMHotKeyStateON
  XIMHotKeyStateOFF

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;; X.h
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  X_PROTOCOL
  X_PROTOCOL_REVISION
  None
  ParentRelative
  CopyFromParent
  PointerWindow
  InputFocus
  PointerRoot
  AnyPropertyType
  AnyKey
  AnyButton
  AllTemporary
  CurrentTime
  NoSymbol
  NoEventMask
  KeyPressMask
  KeyReleaseMask
  ButtonPressMask
  ButtonReleaseMask
  EnterWindowMask
  LeaveWindowMask
  PointerMotionMask
  PointerMotionHintMask
  Button1MotionMask
  Button2MotionMask
  Button3MotionMask
  Button4MotionMask
  Button5MotionMask
  ButtonMotionMask
  KeymapStateMask
  ExposureMask
  VisibilityChangeMask
  StructureNotifyMask
  ResizeRedirectMask
  SubstructureNotifyMask
  SubstructureRedirectMask
  FocusChangeMask
  PropertyChangeMask
  ColormapChangeMask
  OwnerGrabButtonMask
  KeyPress
  KeyRelease
  ButtonPress
  ButtonRelease
  MotionNotify
  EnterNotify
  LeaveNotify
  FocusIn
  FocusOut
  KeymapNotify
  Expose
  GraphicsExpose
  NoExpose
  VisibilityNotify
  CreateNotify
  DestroyNotify
  UnmapNotify
  MapNotify
  MapRequest
  ReparentNotify
  ConfigureNotify
  ConfigureRequest
  GravityNotify
  ResizeRequest
  CirculateNotify
  CirculateRequest
  PropertyNotify
  SelectionClear
  SelectionRequest
  SelectionNotify
  ColormapNotify
  ClientMessage
  MappingNotify
  LASTEvent
  ShiftMask
  LockMask
  ControlMask
  Mod1Mask
  Mod2Mask
  Mod3Mask
  Mod4Mask
  Mod5Mask
  ShiftMapIndex
  LockMapIndex
  ControlMapIndex
  Mod1MapIndex
  Mod2MapIndex
  Mod3MapIndex
  Mod4MapIndex
  Mod5MapIndex
  Button1Mask
  Button2Mask
  Button3Mask
  Button4Mask
  Button5Mask
  AnyModifier
  Button1
  Button2
  Button3
  Button4
  Button5
  NotifyNormal
  NotifyGrab
  NotifyUngrab
  NotifyWhileGrabbed
  NotifyHint
  NotifyAncestor
  NotifyVirtual
  NotifyInferior
  NotifyNonlinear
  NotifyNonlinearVirtual
  NotifyPointer
  NotifyPointerRoot
  NotifyDetailNone
  VisibilityUnobscured
  VisibilityPartiallyObscured
  VisibilityFullyObscured
  PlaceOnTop
  PlaceOnBottom
  FamilyInternet
  FamilyDECnet
  FamilyChaos
  FamilyInternet6
  FamilyServerInterpreted
  PropertyNewValue
  PropertyDelete
  ColormapUninstalled
  ColormapInstalled
  GrabModeSync
  GrabModeAsync
  GrabSuccess
  AlreadyGrabbed
  GrabInvalidTime
  GrabNotViewable
  GrabFrozen
  AsyncPointer
  SyncPointer
  ReplayPointer
  AsyncKeyboard
  SyncKeyboard
  ReplayKeyboard
  AsyncBoth
  SyncBoth
  RevertToNone
  RevertToPointerRoot
  RevertToParent
  Success
  BadRequest
  BadValue
  BadWindow
  BadPixmap
  BadAtom
  BadCursor
  BadFont
  BadMatch
  BadDrawable
  BadAccess
  BadAlloc
  BadColor
  BadGC
  BadIDChoice
  BadName
  BadLength
  BadImplementation
  FirstExtensionError
  LastExtensionError
  InputOutput
  InputOnly
  CWBackPixmap
  CWBackPixel
  CWBorderPixmap
  CWBorderPixel
  CWBitGravity
  CWWinGravity
  CWBackingStore
  CWBackingPlanes
  CWBackingPixel
  CWOverrideRedirect
  CWSaveUnder
  CWEventMask
  CWDontPropagate
  CWColormap
  CWCursor
  CWX
  CWY
  CWWidth
  CWHeight
  CWBorderWidth
  CWSibling
  CWStackMode
  ForgetGravity
  NorthWestGravity
  NorthGravity
  NorthEastGravity
  WestGravity
  CenterGravity
  EastGravity
  SouthWestGravity
  SouthGravity
  SouthEastGravity
  StaticGravity
  UnmapGravity
  NotUseful
  WhenMapped
  Always
  IsUnmapped
  IsUnviewable
  IsViewable
  SetModeInsert
  SetModeDelete
  DestroyAll
  RetainPermanent
  RetainTemporary
  Above
  Below
  TopIf
  BottomIf
  Opposite
  RaiseLowest
  LowerHighest
  PropModeReplace
  PropModePrepend
  PropModeAppend
  GXclear
  GXand
  GXandReverse
  GXcopy
  GXandInverted
  GXnoop
  GXxor
  GXor
  GXnor
  GXequiv
  GXinvert
  GXorReverse
  GXcopyInverted
  GXorInverted
  GXnand
  GXset
  LineSolid
  LineOnOffDash
  LineDoubleDash
  CapNotLast
  CapButt
  CapRound
  CapProjecting
  JoinMiter
  JoinRound
  JoinBevel
  FillSolid
  FillTiled
  FillStippled
  FillOpaqueStippled
  EvenOddRule
  WindingRule
  ClipByChildren
  IncludeInferiors
  Unsorted
  YSorted
  YXSorted
  YXBanded
  CoordModeOrigin
  CoordModePrevious
  Complex
  Nonconvex
  Convex
  ArcChord
  ArcPieSlice
  GCFunction
  GCPlaneMask
  GCForeground
  GCBackground
  GCLineWidth
  GCLineStyle
  GCCapStyle
  GCJoinStyle
  GCFillStyle
  GCFillRule
  GCTile
  GCStipple
  GCTileStipXOrigin
  GCTileStipYOrigin
  GCFont
  GCSubwindowMode
  GCGraphicsExposures
  GCClipXOrigin
  GCClipYOrigin
  GCClipMask
  GCDashOffset
  GCDashList
  GCArcMode
  GCLastBit
  FontLeftToRight
  FontRightToLeft
  FontChange
  XYBitmap
  XYPixmap
  ZPixmap
  AllocNone
  AllocAll
  DoRed
  DoGreen
  DoBlue
  CursorShape
  TileShape
  StippleShape
  AutoRepeatModeOff
  AutoRepeatModeOn
  AutoRepeatModeDefault
  LedModeOff
  LedModeOn
  KBKeyClickPercent
  KBBellPercent
  KBBellPitch
  KBBellDuration
  KBLed
  KBLedMode
  KBKey
  KBAutoRepeatMode
  MappingSuccess
  MappingBusy
  MappingFailed
  MappingModifier
  MappingKeyboard
  MappingPointer
  DontPreferBlanking
  PreferBlanking
  DefaultBlanking
  DisableScreenSaver
  DisableScreenInterval
  DontAllowExposures
  AllowExposures
  DefaultExposures
  ScreenSaverReset
  ScreenSaverActive
  HostInsert
  HostDelete
  EnableAccess
  DisableAccess
  StaticGray
  GrayScale
  StaticColor
  PseudoColor
  TrueColor
  DirectColor
  LSBFirst
  MSBFirst
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  XA_PRIMARY
  XA_SECONDARY
  XA_ARC
  XA_ATOM
  XA_BITMAP
  XA_CARDINAL
  XA_COLORMAP
  XA_CURSOR
  XA_CUT_BUFFER0
  XA_CUT_BUFFER1
  XA_CUT_BUFFER2
  XA_CUT_BUFFER3
  XA_CUT_BUFFER4
  XA_CUT_BUFFER5
  XA_CUT_BUFFER6
  XA_CUT_BUFFER7
  XA_DRAWABLE
  XA_FONT
  XA_INTEGER
  XA_PIXMAP
  XA_POINT
  XA_RECTANGLE
  XA_RESOURCE_MANAGER
  XA_RGB_COLOR_MAP
  XA_RGB_BEST_MAP
  XA_RGB_BLUE_MAP
  XA_RGB_DEFAULT_MAP
  XA_RGB_GRAY_MAP
  XA_RGB_GREEN_MAP
  XA_RGB_RED_MAP
  XA_STRING
  XA_VISUALID
  XA_WINDOW
  XA_WM_COMMAND
  XA_WM_HINTS
  XA_WM_CLIENT_MACHINE
  XA_WM_ICON_NAME
  XA_WM_ICON_SIZE
  XA_WM_NAME
  XA_WM_NORMAL_HINTS
  XA_WM_SIZE_HINTS
  XA_WM_ZOOM_HINTS
  XA_MIN_SPACE
  XA_NORM_SPACE
  XA_MAX_SPACE
  XA_END_SPACE
  XA_SUPERSCRIPT_X
  XA_SUPERSCRIPT_Y
  XA_SUBSCRIPT_X
  XA_SUBSCRIPT_Y
  XA_UNDERLINE_POSITION
  XA_UNDERLINE_THICKNESS
  XA_STRIKEOUT_ASCENT
  XA_STRIKEOUT_DESCENT
  XA_ITALIC_ANGLE
  XA_X_HEIGHT
  XA_QUAD_WIDTH
  XA_WEIGHT
  XA_POINT_SIZE
  XA_RESOLUTION
  XA_COPYRIGHT
  XA_NOTICE
  XA_FONT_NAME
  XA_FAMILY_NAME
  XA_FULL_NAME
  XA_CAP_HEIGHT
  XA_WM_CLASS
  XA_WM_TRANSIENT_FOR
  XA_LAST_PREDEFINED
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;; cursorfont.h
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  XC_num_glyphs
  XC_X_cursor
  XC_arrow
  XC_based_arrow_down
  XC_based_arrow_up
  XC_boat
  XC_bogosity
  XC_bottom_left_corner
  XC_bottom_right_corner
  XC_bottom_side
  XC_bottom_tee
  XC_box_spiral
  XC_center_ptr
  XC_circle
  XC_clock
  XC_coffee_mug
  XC_cross
  XC_cross_reverse
  XC_crosshair
  XC_diamond_cross
  XC_dot
  XC_dotbox
  XC_double_arrow
  XC_draft_large
  XC_draft_small
  XC_draped_box
  XC_exchange
  XC_fleur
  XC_gobbler
  XC_gumby
  XC_hand1
  XC_hand2
  XC_heart
  XC_icon
  XC_iron_cross
  XC_left_ptr
  XC_left_side
  XC_left_tee
  XC_leftbutton
  XC_ll_angle
  XC_lr_angle
  XC_man
  XC_middlebutton
  XC_mouse
  XC_pencil
  XC_pirate
  XC_plus
  XC_question_arrow
  XC_right_ptr
  XC_right_side
  XC_right_tee
  XC_rightbutton
  XC_rtl_logo
  XC_sailboat
  XC_sb_down_arrow
  XC_sb_h_double_arrow
  XC_sb_left_arrow
  XC_sb_right_arrow
  XC_sb_up_arrow
  XC_sb_v_double_arrow
  XC_shuttle
  XC_sizing
  XC_spider
  XC_spraycan
  XC_star
  XC_target
  XC_tcross
  XC_top_left_arrow
  XC_top_left_corner
  XC_top_right_corner
  XC_top_side
  XC_top_tee
  XC_trek
  XC_ul_angle
  XC_umbrella
  XC_ur_angle
  XC_watch
  XC_xterm

  make-XEvent))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(import (primitives sizeof:pointer
                    %get-pointer
                    %peek32u
                    record-constructor
                    void*-rt))

(define (x-query-tree dpy win)

  (let ((root-return      (make-bytevector 4))
        (parent-return    (make-bytevector 4))
        (children-return  (make-bytevector sizeof:pointer))
        (nchildren-return (make-bytevector 4)))

    (XQueryTree dpy
                win
                root-return
                parent-return
                children-return
                nchildren-return)

    (let ((root          (bytevector-u32-native-ref root-return      0))
          (parent        (bytevector-u32-native-ref parent-return    0))
          (children-addr (%get-pointer              children-return  0))
          (nchildren     (bytevector-u32-native-ref nchildren-return 0)))

      (let ((children (make-vector nchildren)))
    
        (let loop ((i 0))

          (cond ((>= i nchildren)
                 (XFree ((record-constructor void*-rt) children-addr))
                 children)
                (else
                 (vector-set! children i (%peek32u (+ children-addr (* i 4))))
                 (loop (+ i 1)))))

        (list root parent children)))))